//Exercise no 23:
//Conditional Tests:

let car:string="subaru";
//test 1:(true)
console.log("Is car =='subaru'?predict true")
console.log(car=="subaru")
//test 2:(true)
console.log("Is car != 'honda'? predict true ")
console.log(car != 'honda')
//test 3:(true)
console.log("Is car.length==6? predict true")
console.log(car.length==6)
//test 4:(true)
console.log("Is car.length !=10? predict true")
console.log(car.length!=10)
//test 5:(true)
console.log("Is car =='subaru'?predict true")
console.log(car=='subaru')
//test 6 :(false)
console.log("Is car =='Subaru'?predict false")
console.log(car=='Subaru')
//test 7:(false)
console.log("Is 10>45 ? predict false")
console.log(10>45)
//test 8:(false)
console.log("Is car.length ==10? predict false")
console.log(car.length ==10)
//test 9 :(false)
console.log("Is car =='Ferrari'?predict false")
console.log(car == 'Ferrari')
//test 10:(false)
console.log("Is 2>8,?predict false")
console.log(2>8)